export const ACCOUNT_SETUP_REQUIRED_MESSAGE = "Complete your password change before using Agora";
export const TEMP_PASSWORD_LENGTH = 12;
export const TEMP_PASSWORD_UPPERCASE_CHARSET = "ABCDEFGHJKMNPQRSTUVWXYZ";
export const TEMP_PASSWORD_LOWERCASE_CHARSET = "abcdefghijkmnpqrstuvwxyz";
export const TEMP_PASSWORD_DIGIT_CHARSET = "23456789";
export const TEMP_PASSWORD_CHARSET =
  TEMP_PASSWORD_UPPERCASE_CHARSET +
  TEMP_PASSWORD_LOWERCASE_CHARSET +
  TEMP_PASSWORD_DIGIT_CHARSET;
